# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: grants-stack-indexer
description: Grants Stack Indexer (Allo v2)

field_selection:
  transaction_fields:
    - "hash"
    - "transactionIndex"
    - "from"

contracts:
  - name: Allo
    handler: src/handlers/Allo.ts
    events:
      - event: PoolCreated(uint256 indexed poolId, bytes32 indexed profileId, address strategy, address token, uint256 amount, (uint256,string) metadata)
      - event: PoolMetadataUpdated(uint256 indexed poolId, (uint256,string) metadata)
      - event: PoolFunded(uint256 indexed poolId, uint256 amount, uint256 fee)
      - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
        name: AlloRoleGranted
      - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
        name: AlloRoleRevoked

  - name: Registry
    handler: src/handlers/Registry.ts
    events:
      - event: ProfileCreated(bytes32 indexed profileId, uint256 nonce, string name, (uint256,string) metadata, address owner, address anchor)
      - event: ProfileMetadataUpdated(bytes32 indexed profileId, (uint256,string) metadata)
      - event: ProfileNameUpdated(bytes32 indexed profileId, string name, address anchor)
      - event: ProfileOwnerUpdated(bytes32 indexed profileId, address owner)
      - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
        name: RegistryRoleGranted
      - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
        name: RegistryRoleRevoked

  - name: Strategy
    handler: src/handlers/Strategy.ts
    events:
      # Registered
      - event: Registered(address indexed recipientId, bytes data, address sender)
        name: RegisteredWithSender
      - event: Registered(address indexed _recipient, bytes _data)
        name: RegisteredWithData

      # TimestampsUpdated
      - event: TimestampsUpdated(uint64 startTime, uint64 endTime, address sender)
        name: TimestampsUpdated
      - event: TimestampsUpdated(uint64 registrationStartTime, uint64 registrationEndTime, uint64 allocationStartTime, uint64 allocationEndTime, address sender)
        name: TimestampsUpdatedWithRegistrationAndAllocation

      # DistributionUpdated
      - event: DistributionUpdated(bytes32 merkleRoot, (uint256,string) metadata)
        name: DistributionUpdatedWithMerkleRoot
      - event: DistributionUpdated((uint256,string) metadata)
        name: DistributionUpdated

      # FundsDistributed
      - event: FundsDistributed(uint256 amount, address grantee, address indexed token, address indexed recipientId)

      # Distributed
      - event: Distributed(address indexed recipientId, address recipientAddress, uint256 amount, address sender)
        name: DistributedWithRecipientAddress
      - event: Distributed(address indexed _recipient, bytes _data)
        name: DistributedWithData
      - event: Distributed(address indexed sender, int96 flowRate)
        name: DistributedWithFlowRate

      # Allocated
      - event: Allocated(address indexed recipientId, uint256 amount, address token, address sender, address origin)
        name: AllocatedWithOrigin
      - event: Allocated(address indexed _recipient, address indexed _sender, uint256 _amount, bytes _data)
        name: AllocatedWithData
      - event: Allocated(address indexed recipientId, uint256 amount, address token, address sender)
        name: AllocatedWithToken
      - event: Allocated(address indexed recipientId, uint256 votes, address allocator)
        name: AllocatedWithVotes
      - event: Allocated(address indexed recipientId, uint8 status, address sender)
        name: AllocatedWithStatus

      # AllocatedWithNft
      - event: AllocatedWithNft(address indexed recipientId, uint256 votes, address nft, address allocator)

      # DirectAllocated
      - event: DirectAllocated(bytes32 indexed profileId, address profileOwner, uint256 amount, address token, address sender)

      # RecipientStatusUpdated
      - event: RecipientStatusUpdated(address indexed recipientId, uint256 applicationId, uint8 status, address sender)
        name: RecipientStatusUpdatedWithApplicationId
      - event: RecipientStatusUpdated(address indexed recipientId, uint8 recipientStatus, address sender)
        name: RecipientStatusUpdatedWithRecipientStatus
      - event: RecipientStatusUpdated(uint256 indexed rowIndex, uint256 fullRow, address sender)
        name: RecipientStatusUpdatedWithFullRow

      # UpdatedRegistration
      - event: UpdatedRegistration(address indexed recipientId, bytes data, address sender, uint8 status)
        name: UpdatedRegistrationWithStatus
      - event: UpdatedRegistration(address indexed recipientId, bytes data, address sender)
        name: UpdatedRegistration
      - event: UpdatedRegistration(address indexed recipientId, uint256 applicationId, bytes data, address sender, uint8 status)
        name: UpdatedRegistrationWithApplicationId

chains:
  # MAINNET
  - id: 1 # Ethereum
    start_block: 18486688
    contracts:
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1
      - name: Strategy
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3

  - id: 10 # Optimism
    start_block: 111678968
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 42 # Lukso
    start_block: 2400000
    # rpc: ${ENVIO_LUKSO_RPC_URL:-https://rpc.mainnet.lukso.network}
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0xB087535DB0df98fC4327136e897A5985E5Cfbd66

  - id: 100 # Gnosis
    start_block: 35900000
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 137 # Polygon
    start_block: 49466006
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  # - id: 250 # Fantom
  #   start_block: 77624278
  #   rpc: ${ENVIO_FANTOM_RPC_URL:-https://rpc.ankr.com/fantom}
  #   contracts:
  #     - name: Registry
  #       address:
  #         - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  #     - name: Strategy
  #     - name: Allo
  #       address:
  #         - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  # - id: 295 # Hedera
  #   start_block: 75239000
  #   rpc: ${ENVIO_HEDERA_RPC_URL:-https://mainnet.hashio.io/api}
  #   contracts:
  #     - name: Registry
  #       address:
  #         - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  #     - name: Strategy
  #     - name: Allo
  #       address:
  #         - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 324 # zkSync Era
    start_block: 31154341
    contracts:
      - name: Registry
        address:
          - 0xaa376Ef759c1f5A8b0B5a1e2FEC5C23f3bF30246
      - name: Strategy
      - name: Allo
        address:
          - 0x9D1D1BF2835935C291C0f5228c86d5C4e235A249

  # - id: 1088 # Metis
  #   start_block: 17860000
  #   rpc: ${ENVIO_METIS_RPC_URL:-https://metis-rpc.publicnode.com}
  #   contracts:
  #     - name: Registry
  #       address:
  #         - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  #     - name: Strategy
  #     - name: Allo
  #       address:
  #         - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 1329 # Sei
    start_block: 78000000
    # rpc: ${ENVIO_SEI_RPC_URL:-https://evm-rpc.sei-apis.com}
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 8453 # Base
    start_block: 6083365
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 42161 # Arbitrum
    start_block: 146489425
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  # - id: 42220 # Celo
  #   start_block: 22257475
  #   rpc: ${ENVIO_CELO_RPC_URL:-https://1rpc.io/celo}
  #   contracts:
  #     - name: Registry
  #       address:
  #         - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  #     - name: Strategy
  #     - name: Allo
  #       address:
  #         - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 43114 # Avalanche
    start_block: 34540051
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 534352 # Scroll
    start_block: 2683205
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

  - id: 11155111 # Sepolia (Testnet)
    start_block: 4617051
    contracts:
      - name: Registry
        address:
          - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
      - name: Strategy
      - name: Allo
        address:
          - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1
